export enum MICROSERVICE {
  USER_SERVICE = 'USER_SERVICE',
  LOG_SERVICE = 'LOG_SERVICE'
}

export const MICROSERVICE_NAMES = {
  [MICROSERVICE.USER_SERVICE]: 'User Service',
  [MICROSERVICE.LOG_SERVICE]: 'Log Service'
};

export const MICROSERVICE_PORTS = {
  [MICROSERVICE.USER_SERVICE]: 8001,
  [MICROSERVICE.LOG_SERVICE]: 8003
};

export enum APPLICATION {
  USER = 'USER',
  LOG = 'LOG'
}

export const APPLICATION_PORTS = {
  [APPLICATION.USER]: 8000,
  [APPLICATION.LOG]: 8002
};
