export enum MICROSERVICE {
  // 用户服务
  USER_SERVICE = 'USER_SERVICE',
  // 日志服务
  LOG_SERVICE = 'LOG_SERVICE',
  // 商品服务
  PRODUCT_SERVICE = 'PRODUCT_SERVICE',
  // 订单服务
  ORDER_SERVICE = 'ORDER_SERVICE',
  // 通用服务
  COMMON_SERVICE = 'COMMON_SERVICE'
}

export const MICROSERVICE_NAMES = {
  [MICROSERVICE.USER_SERVICE]: 'User Service',
  [MICROSERVICE.LOG_SERVICE]: 'Log Service',
  [MICROSERVICE.PRODUCT_SERVICE]: 'Product Service',
  [MICROSERVICE.ORDER_SERVICE]: 'Order Service',
  [MICROSERVICE.COMMON_SERVICE]: 'Common Service'
};

export const MICROSERVICE_PORTS = {
  [MICROSERVICE.USER_SERVICE]: 8001,
  [MICROSERVICE.LOG_SERVICE]: 8003,
  [MICROSERVICE.PRODUCT_SERVICE]: 8005,
  [MICROSERVICE.ORDER_SERVICE]: 8007,
  [MICROSERVICE.COMMON_SERVICE]: 8009
};

export enum APPLICATION {
  USER = 'USER',
  LOG = 'LOG',
  PRODUCT = 'PRODUCT',
  ORDER = 'ORDER',
  COMMON = 'COMMON'
}

export const APPLICATION_PORTS = {
  [APPLICATION.USER]: 8000,
  [APPLICATION.LOG]: 8002,
  [APPLICATION.PRODUCT]: 8004,
  [APPLICATION.ORDER]: 8006,
  [APPLICATION.COMMON]: 8008
};
